apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: nextjs-app
          image: ghcr.io/niklas-mezynski/argo-kurbernets-fullstack-demo:${IMAGE_TAG:-latest}
          ports:
            - containerPort: 3000
          env:
            - name: IMAGE_TAG
              value: "${IMAGE_TAG:-latest}"
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-app
spec:
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
