apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: docker-registry
  namespace: argo
spec:
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      hostNetwork: true # This makes it accessible on the host
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
              hostPort: 5000 # Bind to host port
          env:
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /var/lib/registry
            - name: REGISTRY_HTTP_ADDR
              value: "0.0.0.0:5000"
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
      volumes:
        - name: registry-storage
          hostPath:
            path: /tmp/registry
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: argo
spec:
  selector:
    app: docker-registry
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
  # Note: This service is now mainly for internal cluster DNS resolution
  # The registry is also directly accessible on localhost:5000 due to hostNetwork
