apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /var/lib/registry
            - name: REGISTRY_HTTP_ADDR
              value: "0.0.0.0:5000"
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
      volumes:
        - name: registry-storage
          hostPath:
            path: /tmp/registry
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: argo
spec:
  selector:
    app: docker-registry
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-nodeport
  namespace: argo
spec:
  selector:
    app: docker-registry
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
  type: NodePort
