apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-deployer
  namespace: argo
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
